// ============================================================
// POST /api/complaints/create
// ============================================================
// The citizen's report becomes a database record here, and nowhere else.
//
//   WHAT THE BROWSER IS TRUSTED FOR: the description, the category it
//   picked, and two coordinates. That is all.
//
//   WHAT IT IS NOT TRUSTED FOR: the complaint id, the department, the
//   status, the SLA deadline, the priority, `is_synthetic`, or any
//   timestamp. Every one of those is decided server-side, because every
//   one of them is worth forging. A request that sends `departmentId`
//   or `status` is not rejected — those fields are simply never read,
//   which is the shape least likely to break when the client changes.
//
// One database call. `create_complaint` (0009) writes the civic issue,
// the complaint, two timeline events, the audit event and the
// idempotency ledger in ONE transaction. Doing that as five PostgREST
// requests would leave a complaint with no audit row the first time a
// cold start timed out halfway through.

import { apiError, apiOk, readJsonBody, withErrorHandling } from '../_lib/errors.ts';
import { rpc, isDbConfigured, dbUnavailable, DbRequestError } from '../_lib/db.ts';
import { clientAddress, consume } from '../_lib/rateLimit.ts';
import { verifyAttestation } from '../_lib/attestation.ts';

/**
 * WEB-STANDARD HANDLER, SO THE RUNTIME HAS TO BE DECLARED.
 *
 * Vercel's Node.js runtime invokes `(req, res)` with Express-shaped
 * objects, where `req.headers` is a plain object. Every function in
 * `api/` is written against the Web `Request`/`Response` pair instead —
 * `request.headers.get(...)`, `new Response(...)` — which is the Edge
 * runtime's contract. Without this line the first line of every handler
 * throws `request.headers.get is not a function`, and none of these
 * functions had ever run anywhere for that to show up.
 *
 * Nothing here needs Node: fetch, crypto.subtle, btoa and process.env
 * are all available. Region pinning is a separate question — the
 * database is in ap-south-1, and `regions` in vercel.json is where that
 * belongs if edge distribution ever costs more latency than it saves.
 */
export const config = { runtime: 'edge' };

/** Mirrors src/data/issueCategories.ts. The only categories that exist. */
const CATEGORIES = ['roads', 'garbage', 'water', 'streetlights', 'infrastructure', 'others'];

/**
 * SLA hours per category, server-side.
 *
 * Deliberately not accepted from the request: a client that could choose
 * its own deadline could file every complaint as a four-hour emergency.
 */
const SLA_HOURS: Record<string, number> = {
  water: 24,
  streetlights: 48,
  roads: 72,
  garbage: 24,
  infrastructure: 96,
  others: 72,
};

const MAX_DESCRIPTION = 5000;
const MAX_TITLE = 300;

/** Gwalior's bounding box, generously drawn. */
const CITY_BOUNDS = { minLat: 25.6, maxLat: 26.9, minLng: 77.5, maxLng: 78.9 };

function str(value: unknown, max: number): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > max) return null;
  return trimmed;
}

function num(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

interface CreateResult {
  complaintId: string;
  civicIssueId: string;
  departmentId: string | null;
  status: string;
  slaDueAt: string;
  createdAt: string;
  replayed: boolean;
}

async function handler(request: Request): Promise<Response> {
  if (request.method !== 'POST') {
    return apiError('VALIDATION_ERROR', 'Unsupported request.');
  }

  const body = await readJsonBody(request);
  if (!body) return apiError('VALIDATION_ERROR', 'Expected a JSON body.');

  if (!isDbConfigured()) return dbUnavailable();

  // ----------------------------------------------------------
  // Idempotency key
  // ----------------------------------------------------------
  // Generated by the client per SUBMISSION (not per request), so a retry
  // after a timeout carries the same key and returns the same complaint.
  // Validated for shape only: it is an opaque key, and its uniqueness is
  // enforced by the ledger's primary key rather than by trusting it.
  const idempotencyKey =
    str(body.idempotencyKey, 200) ?? str(request.headers.get('idempotency-key'), 200);
  if (!idempotencyKey || !/^[A-Za-z0-9_:-]{8,200}$/.test(idempotencyKey)) {
    return apiError('VALIDATION_ERROR', 'A valid submission key is required.');
  }

  // ----------------------------------------------------------
  // Rate limit
  // ----------------------------------------------------------
  // After the key check so a retry of an accepted submission is not
  // counted twice, and before any database write.
  const limited = await consume('complaint:create:ip', clientAddress(request));
  if (!limited.allowed) {
    return apiError('RATE_LIMITED', 'Too many reports from this connection. Please wait a moment.', {
      retryAfter: limited.retryAfter,
    });
  }

  // ----------------------------------------------------------
  // Validate
  // ----------------------------------------------------------
  const cityId = str(body.cityId, 64);
  if (!cityId) return apiError('VALIDATION_ERROR', 'A city is required.');

  const category = str(body.category, 64);
  if (!category || !CATEGORIES.includes(category)) {
    return apiError('VALIDATION_ERROR', 'Choose one of the listed issue categories.');
  }

  const description = str(body.description, MAX_DESCRIPTION);
  if (!description) {
    return apiError('VALIDATION_ERROR', `Describe the issue in up to ${MAX_DESCRIPTION} characters.`);
  }

  const title = str(body.title, MAX_TITLE) ?? 'Civic issue';

  // The CONFIRMED issue location. Required — a complaint with no place
  // is not actionable by anyone.
  const lat = num(body.lat);
  const lng = num(body.lng);
  if (lat === null || lng === null) {
    return apiError('VALIDATION_ERROR', 'Confirm the location of the issue on the map.');
  }
  if (lat < CITY_BOUNDS.minLat || lat > CITY_BOUNDS.maxLat ||
      lng < CITY_BOUNDS.minLng || lng > CITY_BOUNDS.maxLng) {
    // Rejected rather than silently accepted: a complaint pinned outside
    // the city cannot be routed to a department that could act on it.
    return apiError('VALIDATION_ERROR', 'That location is outside the area this service covers.');
  }

  // Device GPS. Optional, and NEVER substituted for the confirmed
  // location — they answer different questions (spec §37).
  const gpsLat = num(body.gpsLat);
  const gpsLng = num(body.gpsLng);
  const gpsValid =
    gpsLat !== null && gpsLng !== null &&
    gpsLat >= -90 && gpsLat <= 90 && gpsLng >= -180 && gpsLng <= 180;

  const locationSource = body.locationSource === 'manual' ? 'manual' : 'gps';

  // ----------------------------------------------------------
  // Identity — from the attestation ONLY
  // ----------------------------------------------------------
  //
  //   `body.identityReference` AND `body.identityVerified` ARE IGNORED.
  //   They used to be read straight through, which let any caller post
  //   `identityVerified: true` with a stranger's reference and have it
  //   stored as fact. The only thing trusted now is a token this server
  //   signed itself, after checking an OTP.
  //
  // Absent or unacceptable, the complaint is filed ANONYMOUSLY rather
  // than refused. An unverified report of a burst water main is still a
  // burst water main, and §10 says a citizen needs no account to file —
  // what verification buys is the ability to track it later, not the
  // right to report.
  const identity = await verifyAttestation(body.identityAttestation);

  if (body.identityAttestation && !identity) {
    // Present but bad — forged, edited, expired, or minted by a
    // deployment with a different secret. Distinguished from "absent"
    // because silently downgrading to anonymous would hide the failure
    // from a citizen who believes they verified.
    return apiError('AUTH_REQUIRED', 'Your verification has expired. Please verify again.');
  }

  // ----------------------------------------------------------
  // Create
  // ----------------------------------------------------------
  let result: CreateResult;
  try {
    result = await rpc<CreateResult>('create_complaint', {
      p_idempotency_key: idempotencyKey,
      p_city_id: cityId,
      p_category: category,
      p_title: title,
      p_description: description,
      p_lat: lat,
      p_lng: lng,
      p_locality: str(body.locality, 200),
      p_address: str(body.address, 500),
      p_location_source: locationSource,
      p_gps_lat: gpsValid ? gpsLat : null,
      p_gps_lng: gpsValid ? gpsLng : null,
      p_gps_accuracy_m: gpsValid ? num(body.gpsAccuracy) : null,
      p_gps_captured_at: gpsValid && typeof body.gpsCapturedAt === 'string' ? body.gpsCapturedAt : null,
      // From the ATTESTATION, never from the body. See the block above.
      p_identity_reference: identity?.ref ?? null,
      p_identity_method: identity?.method ?? null,
      p_identity_masked: identity?.masked ?? null,
      p_identity_verified: identity !== null,
      p_severity: 'medium',
      p_priority_score: 50,
      // Server-chosen. See SLA_HOURS.
      p_sla_hours: SLA_HOURS[category] ?? 72,
      // Never client-settable: this flag is what keeps demo rows out of
      // production aggregates, so a browser must not be able to set it.
      p_is_synthetic: false,
    });
  } catch (err) {
    // The named raises from create_complaint arrive in the PostgREST body,
    // not in the Error's own message — `err.message` is only
    // "db_request_failed_400". Matching on that alone made every mapping
    // below unreachable and turned an inactive city into a 500.
    const detail = err instanceof DbRequestError ? err.detail : '';
    const message = `${err instanceof Error ? err.message : ''} ${detail}`;

    // Mapped to sentences; the raw text stays in the log, because it
    // names columns, constraints and functions.
    console.error('[complaints/create] failed', { message: message.slice(0, 300) });

    if (message.includes('city_not_active')) {
      return apiError('VALIDATION_ERROR', 'Reporting is not open for that city yet.');
    }
    if (message.includes('invalid_coordinates')) {
      return apiError('VALIDATION_ERROR', 'That location could not be read. Please set it again.');
    }
    if (message.includes('category_required') || message.includes('description_too_long')) {
      return apiError('VALIDATION_ERROR', 'Please check the category and description and try again.');
    }
    return apiError('INTERNAL_ERROR', 'We could not file your report just now. Please try again.');
  }

  // A replay returns 200 with the original complaint; a new one returns
  // 201. Both carry the same body, so the client needs no special case.
  return apiOk(result, result.replayed ? 200 : 201);
}

export default withErrorHandling(handler);
